# Generated by Django 5.0.1 on 2024-09-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pgvector", "0002_initial"),
        (
            "wagtail_vector_index",
            "0002_rename_embedding_model",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pgvectorembedding",
            name="embedding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtail_vector_index.Document",
            ),
        ),
    ]
