# Generated by Django 5.0.1 on 2024-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pgvector", "0003_alter_pgvectorembedding_embedding"),
        ("wagtail_vector_index", "0003_adjust_document_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pgvectorembedding",
            name="unique_pgvector_embedding_per_index_and_dimensions",
        ),
        migrations.RenameField(
            model_name="pgvectorembedding",
            old_name="embedding",
            new_name="document",
        ),
        migrations.AddConstraint(
            model_name="pgvectorembedding",
            constraint=models.UniqueConstraint(
                fields=("document", "index_name", "embedding_output_dimensions"),
                name="unique_pgvector_embedding_per_index_and_dimensions",
            ),
        ),
    ]
