# Generated by Django 4.2.7 on 2023-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pgvector", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pgvectorembedding",
            name="embedding_output_dimensions",
            field=models.PositiveIntegerField(null=True, db_index=True),
        ),
    ]
