# Generated by Django 4.2.7 on 2023-12-05 11:33

from django.db import migrations


def forwards(apps, schema) -> None:
    PgvectorEmbedding = apps.get_model("pgvector", "PgvectorEmbedding")
    for embedding in PgvectorEmbedding.objects.filter(
        embedding_output_dimensions__isnull=True
    ).iterator():
        embedding.embedding_output_dimensions = len(embedding.vector)
        embedding.save(update_fields=["embedding_output_dimensions"])


class Migration(migrations.Migration):
    dependencies = [
        ("pgvector", "0003_pgvectorembedding_embedding_output_dimensions"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
