# Generated by Django 5.0.1 on 2024-09-06 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_vector_index", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Embedding",
            new_name="Document",
        ),
    ]
